# Generated by Django 5.2.6 on 2025-10-13 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text="Date d'envoi du dernier code de vérification", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email vérifié'),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code de vérification à 6 chiffres', max_length=6)),
                ('email', models.EmailField(help_text='Email à vérifier', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text="Date d'expiration du code")),
                ('is_used', models.BooleanField(default=False, help_text='Code utilisé')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Nombre de tentatives')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vérification Email',
                'verbose_name_plural': 'Vérifications Email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'code'], name='accounts_em_user_id_3e04bc_idx'), models.Index(fields=['email'], name='accounts_em_email_483cd6_idx'), models.Index(fields=['expires_at'], name='accounts_em_expires_858ceb_idx')],
            },
        ),
    ]
